name: project
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.16.1
  google_sign_in: ^4.4.4
  cloud_firestore: ^0.13.7
  provider: ^4.3.1
  flutter_spinkit: ^4.1.2
  shared_preferences: ^0.5.8
  progress_dialog: ^1.2.4
  fluttertoast: ^7.0.2
  awesome_dialog: ^1.1.3
  material_design_icons_flutter: 4.0.5345
  form_field_validator: ^1.0.1

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
